- index.js
Fixed error, if the number of items is less than remain,when start props is setted, it would appear unexpected blank.
> Fixed error, if the number of items is less than remain.

- README.md
- index.js
Added two new options `rtagClass` and `wtagClass` to allow setting classes on the root and item wrappers. Both options use the same API as Vue's `v-bind:class`
> Add rtagClass and wtagClass support

- README.md
- index.js
`VirutalScrollList` has a typo, should be `VirtualScrollList`
> Fix typo in class name

- index.js
I'm not sure if you were avoiding this on purpose but there's a flag in vue to mark the scroll as passive. 
https://vuejs.org/v2/guide/render-function.html#Event-amp-Key-Modifiers
This allows chrome to know that you aren't going to disable the scroll. It does mean you have to have a larger `bench` but I found that it made heavy items scroll waaaaay faster.
> Mark the onscroll as passive

- index.js
List height is determined by item height and visible items number (`remain` prop) and this works flawless as long as this number is {Integer}. But... when `remain` prop is set dynamically to {Float} (for ex.: list fills all available vertical space in UI), last item in scrollable list won't be rendered (for ex.: `delta.end` can equal `58.6` for 59 items, so only 58 slots are rendered).
This solution fixes the problem.
> [Fix] Always render all slots

- index.js
I'm trying to use [vue2-perfect-scrollbar](https://www.npmjs.com/package/vue2-perfect-scrollbar) in `vue-virtual-scroll-list`. The only problem that happen is the way to get the offset value.
`vue2-perfect-scrollbar` makes the structure become like this:
So, it needs to check whether the `$refs.vsl` is a Vue component or not to get the correct scrollTop value.
> support component for $refs.vsl

- examples/build/finite-m.js
- examples/build/finite.js
- examples/build/infinite.js
- examples/entries.js
- examples/finite-m/finite.vue
- examples/finite-m/index.html
- examples/finite-m/index.js
- examples/finite-m/item.vue
- index.js
Recently I found that my page crashed when data set increases(about 2000 items, and 1k per item),
visual(size and remain together) was just 50, but the memory use was nearly 1G.
And the [finite live demo](https://tangbc.github.io/vue-virtual-scroll-list/examples/finite/) performs similarly. Maybe it's a memory leak, or a memory waste, simple 100,000 items retain 64M default , and 150M maximum after scrolling up and down.
50 'keeps' size and all vnodes default, more vnodes and vueComponent are created but not deleted after.
I think it should be a memory waste, virtual item vnodes and components have references with VirtualList in this way. When data set increases, it maybe a memory problem.
```html
<VirtualList :size="50" :remain="6" :bench="44" class="list" :start="startIndex">
<Item …
```
> [Fix] $slots children references cause memory leak, replace by creating the 'keeps' vnodes when it needs

- index.js
When we are defining `remain` value via `containerHeight / size` (because the `containerHeight` is a fixed value), it can lead us to have decimal value on `remain` variable.
Because of it, we will have this extra padding shown by gif below:
<p align="center">
</p>
In the case above, I use `6.6` as the value of `remain`.
> Remove unnecessary padding bottom when decimal number is used

- index.js
- package-lock.json
With the group on the wrapper adding a roll of 'list' the the  virtual-scroll-list, and list-item on the list elements. Generated code would follow the ARIA authoring guidelines for a list.
```html
<virtual-list :size="40" :remain="8" class="scroller" role="list"
inherit
>
<list-item
role="listitem"
:aria-setsize="items.length"
:aria-posinset="index + 1"
v-for="(item, index) of items"
:key="item.id"       
:item="item"
>
</list-item>
</virtual-list>
> Adding a group role to the list item container to allow better aria-support

- .gitignore
- README.md
- package-lock.json
- src/index.js
`vue-virtual-scroll-list` is just awesome! Though, for some industrial purposes, there was a need to add a property that can dynamically change some unimportant styles (in my case, grid styles) of the child element not in the page mode. There has been a `wclass` prop, but it's not enough.
Also, fix typos and misspellings throughout the whole `src/index.js` main file.
> Fix typos and add styling prop for child element

- dist/index.js
- src/item.js
**What kind of this PR?**
Developper experience improvement.
In his question, #176 @MOSMekawy asks how to pass props to the list item component.
This is true that using list of complex objects make it a pain to use. Indeed, every info if the source object is passed as an indivual prop in the component so you have to list them all. For various reasons, this can be fastidious to declare and manipulate.
In this pull request, I have transmitted the whole data-source object under the "data" props.
So you can conveniently declare one Object props in your listed component and use it as you normally do.
Fetching a list of *something* from an API and listing it (and using it in a view component within the list) is then made simpler.
> Do not add each item data as props but wrap it in a single data prop.

- src/index.js
Using `dataSource[dataKey]` has 2 issues:
1. It searches the complete prototype chain (which is unefficient)
2. If the resolved value is `0` or `false` the result is `false` (which isn't intended)
Example:
dataKey is 'id', it's value is zero:
e.g.
{
id: 0
}
So better to be explicit here, e.g. 👍 
` if(dataSource.hasOwnProperty(dataKey)) `
> Using dataSource[dataKey] leads to false results

- README.md
- src/index.js
- src/item.js
- src/props.js
> $scopedSlots for item component

- src/index.js
it will increase speed of VNode-Dom comparison and patch
for example for list of images when new slots added to the list only these images will requested from server (at this moment all 30 will be requested) also no visual glitches when this images downloaded (rerender from previous image to new)
> add key for rendering items

- src/index.js
When the width or height of the outer container changes, the value of props `keeps` will also change, and then need to re-render at this time.
> Response to update when `keeps` changes

- src/virtual.js
**What kind of this PR?**
firstRangeAverageSize is calculated wrong when the first items of the first range have the same size and the following item has a different size. firstRangeTotalSize is then not the sum of all sizes in the first range but is calculated starting from the item with the different size on. 
By dividing then firstRangeTotalSize with the total number of sizes gives a wrong estimated size.
> Calculate correct average size

- src/item.js
Prevent adding `source` and `index` to parent's `extraProps` on each item render.
> fix: extraProps mutation in item render

- src/virtual.js
当数量超过 keeps 的时候，当新增节点的同时，在对底部往上移动会导致 range 计算错误
> fix scroll from bottom will cause range caculate error

- src/index.js
- src/item.js
- src/props.js
> add item slot

- dist/index.js
- docs/index.js
- src/index.js
In certain condition, the method `scrollToBottom` stuck in infinite loop due to this recursive statement.
```javascript
setTimeout(() => {
if (this.getOffset() + this.getClientSize() < this.getScrollSize()) {
this.scrollToBottom()   
}
}, 3)
```
The condition for checking whether scroll is at bottom or not equals to below.
```javascript
scroller.scrollTop + scroller.clientHeight < scroller.scrollHeight
```
It works usually, but in case that clientHeight is non-integer value, there can be a problem.
Since user agents round those values(in my case, Chrome), sum of scrollTop and clientHeight can be 1px smaller than scrollHeight, though scroll is at bottom.
For example, this was my case.
```
real clientHeight: 533.41
real …
```
> Fix infinite scrollToBottom method

- src/virtual.js
1.Since the scroll range of the container = [0 ~ scrollHeight-clientHeight],
so lastCalcIndex is never equal to lastIndex.
2.When not scrolling to the bottom, paddingTop affects the position of the real element in the viewport, but paddingBottom 
does not
3.When scrolling to the bottom, paddingBottom = (last - end) * this.getEstimateSize(),
since last - end = 0, so it is the right result
> Fix remove useless "lastCalcIndex" judgment

- src/virtual.js
Move the scrollbar to the top and keep the mouse pressed long.
After triggering the first totop event, add some data forward.
The first totop event end,the second to top event will no longer be triggered. 
Since after the first trigger, the this.offset becomes 0, and at the second trigger the handleScroll incoming offset is 0.
For now comparing the two leads to this.direction = BEHIND, which estimates a wrong direction, causing the second totop to be no longer triggered.
> fix: totop event was only triggered for once
